baseURL: “”
languageCode: en-us
title: My Study Blog
theme: ["PaperMod"]
publishDir: "public"

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: "Welcome to my blog. I am a software engineer. 
    Here you'll find a lot of cool information about a lot of cool stuff"
  socialIcons:
    - name: github
      url: https://github.com/JCieeeee
    - name: linkedin
      url: https://www.linkedin.com/in/%E4%BD%B3%E6%80%A1-%E9%99%88-a913bb227/

  ShowBreadCrumbs: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30